# Generated by Django 5.0.6 on 2024-11-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre_genre_name_case_insensitive_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, upload_to='book_media/'),
        ),
    ]
