# Generated by Django 5.0.6 on 2024-12-10 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
